meta_product_name: "Lucho"
meta_title: "Lucho - With You!"
meta_description: "empowering children with cancer and their families THROUGH knowledge and trust"
meta_image: "lucho logo.png"                       # should exist in `app/assets/images/`
twitter_account: "" 